definitions:
  types.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  types.RegisterResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      token:
        type: string
      userInfo: {}
    type: object
info:
  contact: {}
paths:
  /api/v1/login/auth_code_login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      - description: 验证码
        in: query
        name: authCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 验证码登录
      tags:
      - 登录/注册
  /api/v1/login/get_UserInfo:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取用户权限
      tags:
      - 用户
  /api/v1/login/get_user_info:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户
  /api/v1/login/register:
    post:
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 注册
      tags:
      - 登录/注册
  /api/v1/login/send_email:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      - description: 验证码
        in: query
        name: authCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: 发送邮件
      tags:
      - 登录/注册
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 登录
      tags:
      - 登录/注册
swagger: "2.0"
