name: Push to Server and Build Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest # 这是 GitHub Actions 的服务器环境 eg: CentOS, Ubuntu, Windows Server, macOS
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.17

      - name: init swagger and push tag
        run:
          echo "version=$(cat ./config/config.ini | grep version | awk -F '=' '{print $2}')" >> $GITHUB_ENV
          echo $version
          go version
          go env -w GOPROXY=https://goproxy.cn,direct
          go get -u github.com/swaggo/swag/cmd/swag
          swag init
          git tag $version
          git checkout $version
          git add .
          git commit -m tag:$version
          git push origin --tags tag:$version

      - name: Push to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 这是你的服务器地址
          username: ${{ secrets.SERVER_USERNAME }} # 这是你的服务器用户名
          password: ${{ secrets.SERVER_PASSWORD }} # 这是你的服务器密码
          script: |
            cd /code/web_server2.0 # 这是你的项目路径
            echo "version=$(cat ./config/config.ini | grep version | awk -F '=' '{print $2}')" >> $GITHUB_ENV
            git fetch origin $version


      - name: Build and Run Docker Compose
        uses: appleboy/ssh-action@master # 这是一个自定义的 Action，用于在服务器上执行命令
        with:
          host: ${{ secrets.SERVER_HOST }} # 这是你的服务器地址
          username: ${{ secrets.SERVER_USERNAME }} # 这是你的服务器用户名
          password: ${{ secrets.SERVER_PASSWORD }} # 这是你的服务器密码
          script: |
            cd /code/web_server2.0 # 这是你的项目路径
            docker-compose stop app nginx  
            # 后台运行docker-compose up --no-deps app nginx
            nohup docker-compose up --no-deps app nginx > /dev/null 2>&1 &
            
          
