name: Push to Server and Build Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest # 这是 GitHub Actions 的服务器环境 eg: CentOS, Ubuntu, Windows Server, macOS
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.17

      - name: init swagger and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          version=$(grep "version =" ./config/config.ini | awk -F= '{print $2}' | tr -d ' ')
          echo VERSION=$version >> $GITHUB_ENV
          echo $version
          git config user.email "your-email@example.com"
          git config user.name "Your Name"
          go env -w GOPROXY=https://goproxy.cn,direct
          go get -u github.com/swaggo/swag/cmd/swag
          swag init
          git checkout -b feature/$version  # 创建一个新分支
          git add .
          git commit -m "Swagger documentation and tag:$version"
          git tag $version
          git push origin $version  # 推送标签
          git push origin feature/$version  # 推送新分支

      - name: Push to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 这是你的服务器地址
          username: ${{ secrets.SERVER_USERNAME }} # 这是你的服务器用户名
          password: ${{ secrets.SERVER_PASSWORD }} # 这是你的服务器密码
          script: |
            cd /code/web_server2.0 # 这是你的项目路径
            git fetch origin $VERSION


      - name: Build and Run Docker Compose
        uses: appleboy/ssh-action@master # 这是一个自定义的 Action，用于在服务器上执行命令
        with:
          host: ${{ secrets.SERVER_HOST }} # 这是你的服务器地址
          username: ${{ secrets.SERVER_USERNAME }} # 这是你的服务器用户名
          password: ${{ secrets.SERVER_PASSWORD }} # 这是你的服务器密码
          script: |
            cd /code/web_server2.0 # 这是你的项目路径
            docker-compose stop app nginx  
            # 后台运行docker-compose up --no-deps app nginx
            nohup docker-compose up --no-deps app nginx > /dev/null 2>&1 &
            
          
